-- -- UTF-8 partout
-- SET client_encoding = 'UTF8';
--
-- -- specialites
-- CREATE TABLE etablissements_specialites
-- (
--     uai              BPCHAR(8)                   NOT NULL,
--     specialite       VARCHAR(15)                 NOT NULL,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_specialites PRIMARY KEY (uai, specialite)
-- );
--
-- ALTER TABLE etablissements_specialites
--     ADD CONSTRAINT fk_specialites_etablissements FOREIGN KEY (uai) REFERENCES etablissements (uai);
--
-- -- sections internationales
-- CREATE TABLE etablissements_sections_internationales
-- (
--     uai              BPCHAR(8)                   NOT NULL,
--     section          VARCHAR(255)                NOT NULL,
--     niveau           VARCHAR(255)                NOT NULL,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_sections_internationales PRIMARY KEY (uai, section, niveau)
-- );
--
-- ALTER TABLE etablissements_sections_internationales
--     ADD CONSTRAINT fk_IPS_etablissements FOREIGN KEY (uai) REFERENCES etablissements (uai);
--
-- -- sports etudes
-- CREATE TABLE etablissements_sports_etudes
-- (
--     uai              BPCHAR(8)                   NOT NULL,
--     sport            VARCHAR(255)                NOT NULL,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_sports_etudes PRIMARY KEY (uai, sport)
-- );
--
-- ALTER TABLE etablissements_sports_etudes
--     ADD CONSTRAINT fk_sports_etudes_etablissements FOREIGN KEY (uai) REFERENCES etablissements (uai);
--
-- -- sections sportives
-- CREATE TABLE etablissements_sections_sportives
-- (
--     uai              BPCHAR(8)                   NOT NULL,
--     sport            VARCHAR(255)                NOT NULL,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_sections_sportives PRIMARY KEY (uai, sport)
-- );
--
-- ALTER TABLE etablissements_sections_sportives
--     ADD CONSTRAINT fk_sections_sportives_etablissements FOREIGN KEY (uai) REFERENCES etablissements (uai);
--
-- -- options (fourre tout)
-- CREATE TABLE etablissements_options
-- (
--     uai              BPCHAR(8)                   NOT NULL,
--     option           VARCHAR(255)                NOT NULL,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_options PRIMARY KEY (uai, option)
-- );
--
-- ALTER TABLE etablissements_options
--     ADD CONSTRAINT fk_options_etablissements FOREIGN KEY (uai) REFERENCES etablissements (uai);
--
-- -- langues
-- CREATE TABLE etablissements_langues
-- (
--     uai              BPCHAR(8)                   NOT NULL,
--     langue           VARCHAR(2)                  NOT NULL,
--     enseignement     VARCHAR(3)                  NOT NULL,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_langues PRIMARY KEY (uai, langue, enseignement)
-- );
--
-- ALTER TABLE etablissements_langues
--     ADD CONSTRAINT fk_langues_etablissements FOREIGN KEY (uai) REFERENCES etablissements (uai);
--
-- -- metadata par annee
-- CREATE TABLE etablissements_metadatas
-- (
--     uai              CHAR(8)                     NOT NULL,
--     annee            INTEGER                     NOT NULL,
--     metadatas        JSONB,
--     created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
--     CONSTRAINT pk_etablissements_metadatas PRIMARY KEY (uai, annee)
-- );
--
-- ALTER TABLE etablissements_metadatas
--     ADD CONSTRAINT FK_METADATAS_ETABLISSEMENTS FOREIGN KEY (uai) REFERENCES etablissements (uai);