spring:
  application:
    name: education-annuaire
  shell:
    interactive:
      enabled: true
  profiles:
    active: local
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enable: true
    baseline-on-migrate: true
    validate-on-migrate: true