spring:
  application:
    name: education-annuaire
  shell:
    interactive:
      enabled: true
  profiles:
    active: prod
  main:
    web-application-type: none
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 500
        order_inserts: true
        order_updates: true
        generate_statistics: false
  flyway:
    #enable: true
    baseline-on-migrate: true
    validate-on-migrate: true
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000

app:
  datasets: shell/datasets