services:
  postgres:
    image: postgres:18.1
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c wal_buffers=64MB
      -c commit_delay=1000
      -c commit_siblings=10
      -c wal_writer_delay=200ms
      -c checkpoint_timeout=1h
      -c checkpoint_completion_target=0.95
      -c max_wal_size=16GB
      -c min_wal_size=4GB
      -c shared_buffers=4GB
      -c work_mem=128MB
      -c maintenance_work_mem=2GB
      -c effective_cache_size=6GB
      -c autovacuum=on
      -c max_connections=20
      -c random_page_cost=1.0
      -c temp_buffers=256MB
      -c log_min_duration_statement=0
      -c log_checkpoints=on

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    networks:
      - myapp-net

  elasticsearch:
    image: elasticsearch:9.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - myapp-net

volumes:
  pgdata:
  es_data:

networks:
  myapp-net: