# ---------------------------------------------
# Paramètres de connexion
# ---------------------------------------------
max_connections = 50  # Limite le nombre maximum de connexions simultanées
listen_addresses = '*'

# ---------------------------------------------
# Paramètres de gestion des logs
# ---------------------------------------------
# logging_collector = on  # Active la collecte des logs dans des fichiers
# log_directory = '/var/lib/postgresql/18/docker/logs'  # Répertoire pour les logs
# log_filename = 'postgresql.log'  # Nom du fichier de log
# log_rotation_age = 1d  # Rotation des logs tous les jours
# log_rotation_size = 10MB  # Rotation des logs après 10 Mo
log_statement = 'ddl'                  # Logue tous les DDL (CREATE, ALTER, DROP) sans condition de durée
log_min_duration_statement = 400       # Logue toutes les requêtes (DML, DDL…) dépassant 400 ms, avec durée
log_duration = on                      # Complète log_statement : ajoute la durée sur les DDL loggués
#log_connections = off  # Désactive les logs de connexion
#log_disconnections = off  # Désactive les logs de déconnexion

# ---------------------------------------------
# Paramètres de performance
# ---------------------------------------------
shared_buffers = 128MB  # Mémoire partagée pour les buffers
work_mem = 4MB  # Mémoire allouée pour les opérations intermédiaires
maintenance_work_mem = 64MB  # Mémoire pour les opérations de maintenance (VACUUM, etc.)
effective_cache_size = 512MB  # Taille estimée du cache disque

# ---------------------------------------------
# Paramètres divers
# ---------------------------------------------
client_min_messages = warning  # Réduit les messages inutiles pour les clients
log_min_messages = warning  # Logue uniquement les messages de niveau WARNING ou supérieur
