name: Java CI - Build & Package

permissions:
  contents: read
  packages: read

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build, test & package all modules
        run: mvn clean verify -DskipTests=false

#      - name: Upload shell module JAR
#        uses: actions/upload-artifact@v4
#        with:
#          name: shell-app
#          path: shell/target/*.jar
#
#      - name: Upload web module JAR
#        uses: actions/upload-artifact@v4
#        with:
#          name: web-app
#          path: web/target/*.jar
